all: part1 part2 part3 part4 part5 part6

part1: part1.o physical.o
	gcc -g -Wall -o part1 part1.c physical.c -lm

part2: part2.o physical.o
	gcc -g -Wall -o part2 part2.c physical.c -lm

part 3: part3.o physical.o
	gcc -g -Wall -o part3 part3.c physical.c -lm -pthread

part4: part4.o physical.o
	gcc -g -Wall -o part4 part4.c physical.c -lm -pthread

part5: part5.o physical.o
	gcc -g -Wall -o part5 part5.c physical.c -lm -pthread

part6: part6.o physical.o
	gcc -g -Wall -o part6 part6.c physical.c -lm -pthread